-- Cantos e flags (etiquetas). Uma flag pertence a um grupo (momento, tempo, ano, tema, outro)
-- e um canto pode ter várias flags, inclusive várias do mesmo grupo.

-- Busca sem acento ("sao" encontra "São"), igual à do site. O Neon também oferece esta extensão.
CREATE EXTENSION IF NOT EXISTS unaccent;

CREATE TABLE flags (
    id          integer       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    group_name  varchar(20)   NOT NULL CHECK (group_name IN ('momento', 'tempo', 'ano', 'tema', 'outro')),
    -- Identificador estável usado em filtros e URLs (ex.: "entrada", "tempo-comum", "A").
    slug        varchar(60)   NOT NULL CHECK (slug ~ '^[A-Za-z0-9]+(-[A-Za-z0-9]+)*$'),
    name        varchar(80)   NOT NULL,
    -- Cor de destaque (tempos litúrgicos), em #RRGGBB.
    color       char(7)       CHECK (color ~ '^#[0-9A-Fa-f]{6}$'),
    position    smallint      NOT NULL DEFAULT 0,
    created_at  timestamptz   NOT NULL DEFAULT now(),
    updated_at  timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT flags_group_slug_key UNIQUE (group_name, slug)
);
COMMENT ON TABLE flags IS 'Etiquetas dos cantos: momento da missa, tempo litúrgico, ano A/B/C, tema...';

CREATE TABLE songs (
    -- BY DEFAULT: a importação preserva os ids do data/songs.json (as missas guardam songId).
    id                 integer       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number             integer       UNIQUE CHECK (number > 0),
    slug               varchar(160)  NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    title              varchar(200)  NOT NULL,
    composer           varchar(200),
    -- Tom original (ex.: "D", "Em", "F#m").
    song_key           varchar(10),
    -- Letra com cifra ("acordes na linha de cima"); refrão marcado com **...**.
    lyrics             text          NOT NULL DEFAULT '',
    audio_url          text,
    audiomack_url      text,
    cifra_pdf_url      text,
    partitura_pdf_url  text,
    -- false = oculto do repertório (em vez de excluir um canto que está em missas).
    active             boolean       NOT NULL DEFAULT true,
    created_by         uuid          REFERENCES users (id) ON DELETE SET NULL,
    updated_by         uuid          REFERENCES users (id) ON DELETE SET NULL,
    created_at         timestamptz   NOT NULL DEFAULT now(),
    updated_at         timestamptz   NOT NULL DEFAULT now()
);
CREATE INDEX songs_title_idx ON songs (title);

CREATE TABLE song_flags (
    song_id  integer  NOT NULL REFERENCES songs (id) ON DELETE CASCADE,
    -- Excluir uma flag tira a etiqueta dos cantos, sem apagar os cantos.
    flag_id  integer  NOT NULL REFERENCES flags (id) ON DELETE CASCADE,
    PRIMARY KEY (song_id, flag_id)
);
CREATE INDEX song_flags_flag_id_idx ON song_flags (flag_id);
