-- =============================================================================
-- Cantos PSJB: schema PostgreSQL 18 convertido do MySQL 5.7.44 (Percona) legado
-- Conversão FIEL: mesmas tabelas, colunas e linhas. O redesenho fica para a Fase 2.
-- Detalhes e mapeamento de tipos: db/postgres/CONVERSAO.md
-- Recriar tudo do zero: python3 db/postgres/migrar.py
-- =============================================================================

\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';
SET client_min_messages = warning;

BEGIN;

DROP TABLE IF EXISTS
    acessos, acessos_online, audios, categorias, configuracoes, contato,
    mensagens_site, modulos, painel_administrativo, usuarios
    CASCADE;

-- No MySQL as colações *_general_ci / *_swedish_ci ignoram maiúsculas e acentos.
-- No Postgres o padrão (ICU pt-BR determinística) diferencia. Para o login continuar
-- encontrando o usuário como antes ('Admin' = 'admin'), usuario e email usam esta colação.
DROP COLLATION IF EXISTS pt_br_ci_ai;
CREATE COLLATION pt_br_ci_ai (provider = icu, locale = 'pt-BR-u-ks-level1', deterministic = false);
COMMENT ON COLLATION pt_br_ci_ai IS
    'pt-BR sem diferenciar maiúsculas/minúsculas nem acentos (equivale ao *_ci do MySQL legado).';

-- -----------------------------------------------------------------------------
-- categorias (InnoDB, utf8)
-- -----------------------------------------------------------------------------
CREATE TABLE categorias (
    categorias_id integer GENERATED BY DEFAULT AS IDENTITY,
    nome          varchar(255),
    ordem         integer,
    CONSTRAINT categorias_pkey PRIMARY KEY (categorias_id)
);
COMMENT ON TABLE  categorias IS 'Categorias (momentos da missa / tempos litúrgicos) dos cantos. Legado: InnoDB utf8.';
COMMENT ON COLUMN categorias.nome  IS 'Nome exibido, ex.: "Comunhão - Páscoa". Alguns nomes legados têm espaço duplo antes do hífen.';
COMMENT ON COLUMN categorias.ordem IS 'Ordem de exibição no site legado (crescente).';

-- -----------------------------------------------------------------------------
-- audios (InnoDB, utf8): os cantos
-- -----------------------------------------------------------------------------
CREATE TABLE audios (
    audios_id    integer GENERATED BY DEFAULT AS IDENTITY,
    nome         varchar(255),
    usuario      varchar(255),
    link         text,
    descricao    text,
    audio_mp3    varchar(255),
    cifra        varchar(255),
    partitura    varchar(255),
    id_categoria integer,
    ativo        boolean DEFAULT true,
    CONSTRAINT audios_pkey PRIMARY KEY (audios_id),
    -- Nome da constraint mantido do legado (sic: "aurio")
    CONSTRAINT categoria_aurio FOREIGN KEY (id_categoria) REFERENCES categorias (categorias_id)
);
CREATE INDEX categoria_aurio ON audios (id_categoria);
COMMENT ON TABLE  audios IS 'Cantos (nome "audios" herdado do CMS legado). Legado: InnoDB utf8.';
COMMENT ON COLUMN audios.nome         IS 'Número e título do canto, ex.: "037 - Agora é tempo de ser Igreja".';
COMMENT ON COLUMN audios.usuario      IS 'Login de quem cadastrou (texto livre; string vazia em parte das linhas). Não é FK.';
COMMENT ON COLUMN audios.link         IS 'Slug da URL do site legado (string vazia em parte das linhas).';
COMMENT ON COLUMN audios.descricao    IS 'Letra e cifra em HTML do editor do CMS, com quebras CRLF preservadas byte a byte.';
COMMENT ON COLUMN audios.audio_mp3    IS 'Caminho relativo do MP3 em uploads/ do servidor legado.';
COMMENT ON COLUMN audios.cifra        IS 'Caminho relativo do PDF da cifra em uploads/ do servidor legado.';
COMMENT ON COLUMN audios.partitura    IS 'Caminho relativo do PDF da partitura em uploads/ (NULL quando não há).';
COMMENT ON COLUMN audios.id_categoria IS 'Categoria do canto (FK categorias).';
COMMENT ON COLUMN audios.ativo        IS 'Legado: int(11) DEFAULT 1 com valores 0/1; convertido para boolean.';

-- -----------------------------------------------------------------------------
-- usuarios (MyISAM, latin1): usuários do painel administrativo legado
-- -----------------------------------------------------------------------------
CREATE TABLE usuarios (
    id            integer GENERATED BY DEFAULT AS IDENTITY,
    nome          varchar(255),
    usuario       varchar(255) COLLATE pt_br_ci_ai NOT NULL,
    senha         varchar(255) NOT NULL DEFAULT '',
    email         varchar(255) COLLATE pt_br_ci_ai,
    permissoes    varchar(255) NOT NULL,
    ultimo_acesso timestamp(0) without time zone,
    ativo         boolean NOT NULL,
    tipo          integer NOT NULL DEFAULT 2,
    token         varchar(255),
    CONSTRAINT usuarios_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE  usuarios IS 'Usuários do painel legado. Legado: MyISAM latin1. NÃO reaproveitar as senhas na Fase 2.';
COMMENT ON COLUMN usuarios.usuario       IS 'Login. Colação pt_br_ci_ai para manter a comparação sem caixa/acento do MySQL.';
COMMENT ON COLUMN usuarios.senha         IS 'ATENÇÃO: hash MD5 sem salt (32 hex). Inseguro: forçar redefinição de senha na Fase 2.';
COMMENT ON COLUMN usuarios.permissoes    IS 'Lista de ids de modulos separados por vírgula, com vírgula final (ex.: "5,8,54,55,").';
COMMENT ON COLUMN usuarios.ultimo_acesso IS 'Data/hora local do servidor legado (America/Sao_Paulo), sem fuso. Legado: datetime.';
COMMENT ON COLUMN usuarios.ativo         IS 'Legado: int(1) NOT NULL com valores 0/1; convertido para boolean.';
COMMENT ON COLUMN usuarios.tipo          IS 'Perfil no painel legado (pelo uso, 1 parece ser administrador e 2 o padrão; confirmar no código PHP).';
COMMENT ON COLUMN usuarios.token         IS 'Token de sessão/recuperação do painel legado (32 hex). Tratar como segredo.';

-- -----------------------------------------------------------------------------
-- modulos (InnoDB, latin1): módulos do CMS (menu do painel)
-- -----------------------------------------------------------------------------
CREATE TABLE modulos (
    id     integer GENERATED BY DEFAULT AS IDENTITY,
    nome   varchar(255) NOT NULL,
    _table varchar(255) NOT NULL,
    codigo text NOT NULL,
    icone  varchar(50) NOT NULL,
    CONSTRAINT modulos_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE  modulos IS 'Módulos do CMS legado (itens do menu do painel). Legado: InnoDB latin1.';
COMMENT ON COLUMN modulos._table IS 'Tabela que o módulo administra (string vazia nos módulos fixos).';
COMMENT ON COLUMN modulos.codigo IS 'Configuração do módulo em JSON (texto). Legado: longtext.';

-- -----------------------------------------------------------------------------
-- configuracoes (MyISAM, latin1): SEO/metadados do site
-- -----------------------------------------------------------------------------
CREATE TABLE configuracoes (
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    titulo     varchar(70),
    descricao  varchar(155),
    palavras   varchar(175),
    adwords    text,
    contato    varchar(255),
    contato_cc text,
    CONSTRAINT configuracoes_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE  configuracoes IS 'Configurações gerais/SEO do site legado (1 linha). Legado: MyISAM latin1.';
COMMENT ON COLUMN configuracoes.palavras IS 'Palavras-chave (meta keywords) separadas por vírgula.';

-- -----------------------------------------------------------------------------
-- contato (InnoDB, latin1)
-- -----------------------------------------------------------------------------
CREATE TABLE contato (
    id          integer GENERATED BY DEFAULT AS IDENTITY,
    titulo      varchar(255),
    subtitulo   varchar(255),
    desctitulo  text,
    rua         varchar(255),
    cidade      varchar(255),
    uf          varchar(255),
    email       varchar(255),
    telefone    varchar(255),
    telefone2   varchar(255),
    bairro      varchar(255),
    numero      varchar(255),
    complemento varchar(255),
    mapa        text,
    horario     text,
    facebook    varchar(255),
    instagram   varchar(255),
    youtube     varchar(255),
    latitude    varchar(255),
    longitude   varchar(255),
    CONSTRAINT contato_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE contato IS 'Dados de contato da paróquia exibidos no site legado (1 linha). Legado: InnoDB latin1.';

-- -----------------------------------------------------------------------------
-- mensagens_site (InnoDB, utf8): formulário "fale conosco"
-- -----------------------------------------------------------------------------
CREATE TABLE mensagens_site (
    id         integer GENERATED BY DEFAULT AS IDENTITY,
    nome       varchar(255) NOT NULL,
    email      varchar(255),
    telefone   varchar(100) DEFAULT 'Não informado',
    cidade     varchar(255),
    mensagem   text,
    enviado_em timestamp(0) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT mensagens_site_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE  mensagens_site IS 'Mensagens enviadas pelo formulário de contato. Contém dados pessoais. Legado: InnoDB utf8.';
COMMENT ON COLUMN mensagens_site.enviado_em IS 'Legado: TIMESTAMP (guardado em UTC pelo MySQL). Instante exato preservado em timestamptz.';

-- -----------------------------------------------------------------------------
-- painel_administrativo (InnoDB, latin1): aparência do painel do CMS
-- -----------------------------------------------------------------------------
CREATE TABLE painel_administrativo (
    id             integer GENERATED BY DEFAULT AS IDENTITY,
    titulo         varchar(255),
    subtitulo      varchar(255),
    imagem_login   varchar(255),
    imagem_logo    varchar(255),
    cor_primaria   varchar(255),
    cor_secundaria varchar(255),
    CONSTRAINT painel_administrativo_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE painel_administrativo IS 'Aparência do painel do CMS legado (1 linha). Legado: InnoDB latin1.';

-- -----------------------------------------------------------------------------
-- acessos (MyISAM, latin1): log de visitas
-- -----------------------------------------------------------------------------
CREATE TABLE acessos (
    id   integer GENERATED BY DEFAULT AS IDENTITY,
    data timestamp(0) without time zone,
    ip   varchar(15) NOT NULL,
    CONSTRAINT acessos_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE  acessos IS 'Log de visitas do site legado. Legado: MyISAM latin1.';
COMMENT ON COLUMN acessos.ip IS 'IPv4 ou IPv6 (15 de 21 linhas são ::1). varchar(15) não comporta IPv6 completo: usar inet na Fase 2.';
COMMENT ON COLUMN acessos.data IS 'Data/hora local do servidor legado (America/Sao_Paulo), sem fuso. Legado: datetime.';

-- -----------------------------------------------------------------------------
-- acessos_online (MyISAM, latin1): visitantes "online" (sem chave primária no legado)
-- -----------------------------------------------------------------------------
CREATE TABLE acessos_online (
    ip   varchar(20) NOT NULL,
    time bigint NOT NULL
);
COMMENT ON TABLE  acessos_online IS 'Visitantes online do site legado. Não tem chave primária nem índice no legado (mantido assim).';
COMMENT ON COLUMN acessos_online.time IS 'Unix epoch em segundos. Legado: int(20) (32 bits); bigint evita o limite de 2038.';

COMMIT;
